### ISSUE TITLE
Pages out of order when converting

### ISSUE THREAD

**Issue by tactiical** [binarynonsense/comic-book-reader#101]
Hiya, me again :) 
I've been running into an issue where pages are incredibly scattered after converting. 
For example: Page 1 - the cover
![image](https://github.com/binarynonsense/comic-book-reader/assets/103299097/083f0300-5ac2-4413-8560-2d0c41a9b333)
Page 2 to 26 - shows pages 148-172 (where it should be showing page 1 onward)
![image](https://github.com/binarynonsense/comic-book-reader/assets/103299097/e67082bb-8a48-49cb-95fc-5f4d09f3a6ae)
![image](https://github.com/binarynonsense/comic-book-reader/assets/103299097/820089b0-cf7f-45a7-9a8d-da8fe5d65092)
![image](https://github.com/binarynonsense/comic-book-reader/assets/103299097/fe293d52-5618-454c-9e94-743bef84fc89)
![image](https://github.com/binarynonsense/comic-book-reader/assets/103299097/2d1693bc-2f09-4de7-99ad-09ea508c1866)
then page 28 jumps to page 218
![image](https://github.com/binarynonsense/comic-book-reader/assets/103299097/a8766fa8-4993-47af-946e-4d156038fbcb)
![image](https://github.com/binarynonsense/comic-book-reader/assets/103299097/ef58895e-16fc-420d-9af4-90d524980c4f)

I checked CbxConverter and it orders the pages fine on the same file so I'm kinda stumped. Gonna have to go back thru everything I've converted and double check it all

**Comment by binarynonsense** [comment]
Which version of ACBR did you use? Does the same happen when using the latest beta (3.3.3-beta6) and the latest stable version (3.3.2)? The only thing I can think of right now is that the original file has multiple folders inside the file and the naming of the files doesn't play well with each other and with how ACBR used to reorganize the files (previous versions until the latest betas just copied the image files without folders, but I recently changed that)

**Comment by binarynonsense** [comment]
I've released a new stable version ([v3.4.0](https://github.com/binarynonsense/comic-book-reader/releases/tag/v3.4.0)) that includes the changes I mentioned from the latest betas. If you can give it a try, let me know if the issue still happens with it.

**Comment by tactiical** [comment]
> I've released a new stable version ([v3.4.0](https://github.com/binarynonsense/comic-book-reader/releases/tag/v3.4.0)) that includes the changes I mentioned from the latest betas. If you can give it a try, let me know if the issue still happens with it.

Seems to be all fixed with the new version. Thanks a bunch :)

**Comment by binarynonsense** [comment]
No problem! Glad it's now fixed.
