### ISSUE TITLE
[Feature] Add language translator

### ISSUE THREAD

**Issue by rtritto** [binarynonsense/comic-book-reader#102]
Add translation of a page (select text) or an image (select text with OCR) from a language to another one.

Similar app: [EPUB Book Translator](https://apps.microsoft.com/detail/9ng5w40jc1fw)
Similar tool: [ePUB Translator](https://github.com/quantrancse/epub-translator)

**Comment by binarynonsense** [comment]
Thanks for the feature suggestion!

Sorry, I'm not planning on adding something like this. 

I could some day look into adding translation to the already existing "page>extract text" tool if there's an easy way to do it (if google translate or a similar service has a free and simple to use api, which I don't know) if that sounds useful, but no promises even about that.

**Comment by binarynonsense** [comment]
Also, let me know if what I mentioned about 'adding a translation option to the already existing "page>extract text" tool' for comic book pages / images is something you'd find useful (right now it would be out of scope but may be something I'd try adding at some point), but if you meant specifically for text epubs (from the other issue you opened now I'm thinking that may be the case), sorry but that's definitely out of scope for the project.

**Comment by rtritto** [comment]
> Also, let me know if what I mentioned about 'adding a translation option to the already existing "page>extract text" tool' for comic book pages / images is something you'd find useful (right now it would be out of scope but may be something I'd try adding at some point), but if you meant specifically for text epubs (from the other issue you opened, now I'm thinking that may be the case), sorry but that's definitely out of scope for the project.

"Extract text" is another feature. As in other apps, would be convenient an auto-translate or a select-and-translate for EPUBs and comic books.

**Comment by binarynonsense** [comment]
What I meant is: a straight select-and-translate/autotranslate option directly on the viewer is out of scope for the project, at most I could think about / try adding a translation option to the already existing "page>extract text" tool (it works with comic book pages / images, not EPUB ebooks), if it is something people would really find useful and I have the time and am able in the future, but I'm not sure if that would make the extract text tool's interface too cumbersome/bloated or would interest enough people, yourself included, to be worth the time/effort.

**Comment by binarynonsense** [comment]
I'm closing this one, as it seems that the feature you specifically wanted is out of scope, but don't hesitate to reopen it and/or keep chatting about it here if you have more to add.
