### ISSUE TITLE
[Feature] Change colors

### ISSUE THREAD

**Issue by rtritto** [binarynonsense/comic-book-reader#103]
Add options to customize colors of text and background.
Can be used some themes (e.g. light/dark mode).

**Comment by binarynonsense** [comment]
> Can be used some themes (e.g. light/dark mode).

You can already choose between some premade color themes, including light and dark ones, in the preferences. Have you tried that?

> Add options to customize colors of text and background.

I may add the option to load custom themes in the future if that's something people would like and the premade ones are not enough.

Thanks for the feedback!

**Comment by rtritto** [comment]
> Preferences --> Appearance --> Text and colors --> Color Theme

This setting only change the layout of app and not the content (text and background) of pages.

**Comment by binarynonsense** [comment]
Oh, yes, I thought you meant the app's colors.

Then I assume you are you talking specifically about the color of the text and background when viewing epub text files, not comic books ones.

ACBR is mainly a comic book reader and I only made it possible to also be able to open/view text epubs, not comic book ones (images only) as was the only option originally, as an afterthought.
 The viewer for that is quite basic and not the focus of the app (I could even take it out in the future if it becomes a problem to maintain at some point), but I could see if I can add the option to choose between light (white background and black text) and dark (black background and white text)... is that what you were suggesting?

**Comment by rtritto** [comment]
> Then I assume you are you talking specifically about the color of the text and background when viewing epub text files, not comic books ones.

My use case is with the EPUBs, but this feature could be done with comic books too.

> The viewer for that is quite basic and not the focus of the app (I could even take it out in the future if it becomes a problem to maintain at some point), but I could see if I can add the option to choose between light (white background and black text) and dark (black background and white text)... is that what you were suggesting?

Yes, I need the dark one (black background and white text).

**Comment by binarynonsense** [comment]
I just uploaded a new beta, [v3.5.0-beta2](https://github.com/binarynonsense/comic-book-reader/releases/tag/v3.5.0-beta2), that adds and experimental setting to the preferences to choose between light and dark modes for the EPUB ebooks (it's at the bottom of the Appearance section of the Preferences). Let me know if you try it and it's what you wanted.

**Comment by rtritto** [comment]
I tested the setting `Epubs Book --> Color Mode --> Dark Mode` and it works.
The choice of colors (Text and Background) could be improved by choosing the color through the color picker (RGB).

**Comment by binarynonsense** [comment]
Great. For now, this is as far as I'll go, as it is what we talked about

> Yes, I need the dark one (black background and white text).

so I assume it's good enough. But maybe some day I'll add support for custom colors.

Now that you've confirmed that it works, I'll close the issue but feel free to add more to the conversation whenever you want and I'll let you know here if at some point I add more options related to this.

**Comment by binarynonsense** [comment]
Hope you understand what I mean when I say that "for now, this is as far as I'll go"... It's not that I don't appreciate your feedback, I'm getting ready for the next stable release and have to cut adding new features at some point. I appreciate your new suggestions and maybe I'll add custom colors at some point as you mentioned, but I'm hoping that given that the light and dark modes is what we talked about before, it's a good enough addition for you by itself.

**Comment by binarynonsense** [comment]
I just released the next stable version, 3.5.0 and, as I had a bit of time to work on it, it includes a custom mode option in the EPUB Ebooks color mode preference. Once selected you can choose the text and background colors, hope you like it!
