### ISSUE TITLE
[Feature Request] Bulk Conversion/Recursive Directory Search

### ISSUE THREAD

**Issue by stuntguy3000** [binarynonsense/comic-book-reader#105]
Hi there, love the application - works great.

I have a problem where I have a large directory with hundreds of nested folders (a catalog) of CBR/CBZ files, many many folders deep. I've been looking for a tool for which I can specify a parent directory and convert the entire catalog in a single sweep.

**For example:**
Parent Folder: Comics
 - Comic Series A
    - 2020
      - Comic A.cbz
      - Comic B.cbr
    - 2021
      - Comic A.cbz
      - Comic B.cbr
 - Comic Series B
    - 2020
      - Comic A.cbz
      - Comic B.cbr
    - 2021
      - Comic A.cbz
      - Comic B.cbr

As a user, I'd like to be able to **Convert all comics in "Comics" Folder/Subfolders to PDF**

**Outcome:**
Parent Folder: Comics
 - Comic Series A
    - 2020
      - Comic A.cbz
      - Comic B.cbr
      - Comic A.pdf
      - Comic B.pdf
    - 2021
      - Comic A.cbz
      - Comic B.cbr
      - Comic A.pdf
      - Comic B.pdf
 - Comic Series B
    - 2020
      - Comic A.cbz
      - Comic B.cbr
      - Comic A.pdf
      - Comic B.pdf
    - 2021
      - Comic A.cbz
      - Comic B.cbr
      - Comic A.pdf
      - Comic B.pdf

Thanks!

**Comment by binarynonsense** [comment]
I'll need to think a bit more about how I'd do it, so I'm not sure, but I don't think I'll be adding something like that at least for now, as it'd probably require reworking how some things are structured, UI changes, maybe a specific tool so the normal one doesn't get too complex... and I don't currently have the time. I can only promise to add it to my TODO list to think about it and make some tests at some point if I can, as it seems like something useful.

Thanks for the feature request!

**Comment by binarynonsense** [comment]
I just uploaded a new beta, [v3.5.0-beta2](https://github.com/binarynonsense/comic-book-reader/releases/tag/v3.5.0-beta2), that adds some options to the conversion tool, from the changelog:

-  Added the option to include folders in the input list of the convert and create comics tools. The folders in the input list will be searched for valid files to use during the conversion/creation process (there's an advanced option to enable searching them recursively and another to select which file types are valid).
-  Added an option in the convert comics tool to select between choosing an output folder for all files or saving each one in the same folder as its corresponding input file.
-  Added an advanced option in the convert comics tool to select between overwriting the output file if it already exists, save it with a name not already in use or skip saving it.

If everything works correctly, a combination of these should let you achieve what you wanted. Let me know if you give it a try.

**Comment by binarynonsense** [comment]
Just released the next stable release containing the changes I mentioned so I'll close this issue.
