### ISSUE TITLE
[FR] - 7zip distribution

### ISSUE THREAD

**Issue by vatterspun** [binarynonsense/comic-book-reader#11]
I set up with the maximum settings in 7zip and got the current Comic Book Reader distro to 96 megs (it's 66% smaller than the current distro).  On my 5 year old machine it only took about 4 minutes to generate and will save a lot of bandwidth.

It's also possible to distribute a self-extracting 7z file for users that don't have a 7zip-compatible extraction tool.  But my own focus is on the 7z file.

**Comment by binarynonsense** [comment]
Thanks for the suggestion! I've added a new self-extracting file (7z ultra compressed) for the Windows version to the downloads.

**Comment by vatterspun** [comment]
Confirmed, thanks
