### ISSUE TITLE
[FR] - Additional format support

### ISSUE THREAD

**Issue by vatterspun** [binarynonsense/comic-book-reader#12]
Really liking this program so I'll go ahead and request a few more formats in addition to the current set.  None of these are crucial, just nice to have.  Listing roughly in order of preference with the least valuable at the bottom.

* CB7 (7zip-compressed files)
* AVIF - open source high compression JPEG replacement
* Password-protected archives and PDF files
* DjVu and individual or multi-page TIFF support (I rarely see these)

**Comment by binarynonsense** [comment]
From a quick initial research adding avif as an allowed image format inside comic files should be easy. I have never used it, so I may be wrong, but I'll add it to my list of things to try. 
cb7 support is something I thought about adding but haven't found a pure javascript library that does what I need so far, and it isn't a format I've ever found the need to use myself or seen used, so it's not really a priority for me (same for djvu). 
The rest I'm not sure I'll add, I may look into password protection, but for comic book files seems a bit unnecessary, and unlike avif  I don't think tiff is supported by chrome/electron which makes adding support for it less straightforward.
Anyway, I'll keep all of this in mind in case I have the time to research them more properly and try adding them some day.

**Comment by vatterspun** [comment]
> adding avif as an allowed image format inside comic files should be easy

Great news, thanks.  I'm hoping everything to moves over to AVIF in the years ahead.

> CB7 ... isn't a format I've ever found the need to use myself or seen used

I've seen it a few places, but yeah it's not common.  As a format it's not going see a major size difference between CBZ and CB7.  Unless it's a large archive with 100+ pages or lots of metadata.

> I may look into password protection, but for comic book files seems a bit unnecessary, 

Agreed.  However, I think ACBR will get used as a picture viewer / slideshow player as well.  And in that space, being able to share photos with some kind of password is a welcome addition.

Thanks for your response.

**Comment by binarynonsense** [comment]
I've uploaded a new [beta version](https://github.com/binarynonsense/comic-book-reader/releases/tag/v2.1.0-beta1) that adds support for the _avif_ image format to the reader and some of the tools.

**Comment by binarynonsense** [comment]
I just uploaded another beta ([2.1.0-beta2](https://github.com/binarynonsense/comic-book-reader/releases/tag/v2.1.0-beta2)) that adds support for password protected pdf, cbz (AES encryption not supported, only zipCrypto), and cbr files in the reader.

**Comment by binarynonsense** [comment]
The new [2.1.0 version](https://github.com/binarynonsense/comic-book-reader/releases/tag/v2.1.0) is now available and includes support for .cb7 files. With this I think I've added everything in this issue except for djvu and tiff support which, at least for now, I don't think I'll be adding.
