### ISSUE TITLE
[FR] Additional zoom options

### ISSUE THREAD

**Issue by vatterspun** [binarynonsense/comic-book-reader#14]
The program's default zoom settings are generally fine for what I need but when I'm using my laptop, it would be nice to have some additional views.

**Current behavior**

1. Zoom to width
2. Zoom to height 
3. The above two but with full screen enabled 

** Requested behavior**

* Optional scroll wheel zooming, ideally CTRL+scroll wheel to zoom in or out
* Other custom or pre-set zoom settings, mostly for when images have a large side-border

---

EDIT: quick clarification here: what I mean when I say "using my laptop" is that it has a much smaller resolution and makes it hard to view some files at the current zoom sizes.

**Comment by binarynonsense** [comment]
I'll add these to my 'think about' list, but no promises :)

**Comment by vatterspun** [comment]
> I want to keep the interface/options as minimal/simple as possible 

While I think my idea is important but so is the next person and pretty soon you've got a really cluttered interface.  So that makes sense.  Feel free to close this issue if you decide against it.

**Comment by binarynonsense** [comment]
I just uploaded another beta ([2.1.0-beta2](https://github.com/binarynonsense/comic-book-reader/releases/tag/v2.1.0-beta2)) that includes a new view, scale to height, allowing setting the zoom scale to one of the preset values or a custom one. Also, the view's zoom can now be increased or decreased from the menus or using 'ctrl++', 'ctrl+-', or 'ctrl+scroll wheel'.
