### ISSUE TITLE
Beyond the Page: Immersive Elements

### ISSUE THREAD

**Issue by AhayriSG** [binarynonsense/comic-book-reader#169]
While desktop CBZ+PDF viewer software like SumatraPDF, CDisplayEx, and ACBR offer impressive functionality, they often lack immersive features that can enhance the reading experience. For example, graphical elements like shadows in the gutter area (missing in SumatraPDF as far as i know) and flipbook animations with sound, as seen in [Heyzine's Flipbook Viewer](https://heyzine.com/). These kind of features could significantly elevate the sense/feeling of immersion. SumatraPDF and CDisplayEx are prime examples of software that could benefit from such features. ACBR's implementation of these elements would set it apart from other popular viewers.

**Comment by binarynonsense** [comment]
Thanks for the feedback!

ACBR is designed to be as simple and minimalistic as possible so adding flipbook animations, extra shadows... are currently outside the scope of the project (and wouldn't even be possible until I add a double page mode, which I don't know when/if will happen, and some changes in how the reader works). Sorry, I may add an option to play a sound on page turns, but the rest I don't think I'll be adding at least for now, I hope you understand.
