### ISSUE TITLE
Hide "Page Number"

### ISSUE THREAD

**Issue by rtritto** [binarynonsense/comic-book-reader#170]
Add the _hide option_ for "Page Number" (I would use it as _default_)

![immagine](https://github.com/user-attachments/assets/8199260e-d967-4b53-a8d0-e16c27cd9171)

because the page number counter are already in the bar

![immagine](https://github.com/user-attachments/assets/e0127b3c-bb34-4306-9b62-4121f7fcaa48)

---

Note: I would rename "Page Number" to something like "Page Counter"

**Comment by binarynonsense** [comment]
You can already show/hide the page number and other UI elements from the View > Layout Menu:

![image](https://github.com/user-attachments/assets/a6d76617-b299-4787-9c04-c0a4c76ef4b3)

**Comment by rtritto** [comment]
Thanks (imo the issue can be closed)
