### ISSUE TITLE
Feature request: Ability to adjust saturation when converting

### ISSUE THREAD

**Issue by oli3012** [binarynonsense/comic-book-reader#173]
I love this tool for converting comics to PDF or epub to read on a color e-ink device, it's blazing fast! Color on this type of device is very muted, and for some files it would help a lot to be able to boost saturation. If it's not too much trouble to add I think it's a feature that could be handy for numerous use cases.

Anyway, thank you for making it free and open-source, it's the best!

**Comment by binarynonsense** [comment]
Glad you like the tool and thanks for the feature request!

I think adding an advanced option to apply some basic tweaks to the images (saturation, brightness, ...) during the conversion should be doable and something that, as you say, some people may find useful so I'll add it to my TODO list to at least take a look at it / make some tests in the future. 

No promises as to if or when but I'll definitely try someday if I can.

**Comment by binarynonsense** [comment]
I just released a new beta, [3.7.0-beta1](https://github.com/binarynonsense/comic-book-reader/releases/tag/v3.7.0-beta1), that adds the possibility of applying some simple image operations to the pages (brightness and saturation) during the conversion to the advanced options of the comics converter tool.

![image](https://github.com/user-attachments/assets/01be1b0f-70a6-4c3a-a15c-60052aaca8e1)

Let me know if you give it a try and, hopefully, does what you wanted.

**Comment by cdrintherrieno** [comment]
Wow! It works great, colors are much better now, and the image stays sharp. Thank you so much for taking the time to integrate this, it's very appreciated :)

**Comment by binarynonsense** [comment]
No problem, glad it works as expected, thanks for testing it!
