### ISSUE TITLE
Feature request: turn page with scroll wheel

### ISSUE THREAD

**Issue by Kered** [binarynonsense/comic-book-reader#20]
Would it be possible to add the ability to turn the pages via a mouse scroll wheel?  CTRL+the wheel works well for zooming in and feels natural since many other programs work that way too.  But I'm used to turning pages on my PC via the mouse wheel, thanks to just about every PDF viewer I've ever used, and it would be nice if it worked that way in this reader too.  Thanks for your consideration!

**Comment by binarynonsense** [comment]
I was thinking about adding it to the 'fit to height' zoom mode not long ago, so that's something I'd like to include when I have the chance to work on a future version. 
With other zoom modes the mouse wheel is used to scroll the page up and down, so I don't see a good way to have it do both things. Maybe I could check if the user keeps trying to scroll down after reaching the bottom (same for the top side) and turn the page if so... but that may be confusing and hard to find the right spot/amount.
Would it be enough for you to have it available in the 'fit to height' mode or it's something you'd like in every mode? If the latter, what do you think about my doubts of how to implement both being able to scroll and turn the page with the wheel?.
Thanks for taking the time to create this feature suggestion!

**Comment by Kered** [comment]
> Maybe I could check if the user keeps trying to scroll down after reaching the bottom (same for the top side) and turn the page if so... but that may be confusing and hard to find the right spot/amount. 

That's pretty much exactly how it works in PDF readers like Adobe Reader and Foxit PDF Reader.  I'm used to that and think it would be helpful here, but I'm just one data point and it's ultimately your call.  It's not a huge problem to ultimately have to use the arrow keys to turn pages instead; it just always trips me up at least once when I load up your program.

>Would it be enough for you to have it available in the 'fit to height' mode or it's something you'd like in every mode? If the latter, what do you think about my doubts of how to implement both being able to scroll and turn the page with the wheel?. Thanks for taking the time to create this feature suggestion!

I think that's a fair compromise too!  If the page is guaranteed to always be fully in view, then allowing the mouse wheel to turn the page seems ok.  The only issue with that I can think of is that UI controls that aren't consistent from one view mode to the next can be confusing to the user.  It might be best to leave out a mouse wheel page turn option in that case.

One last alternative might be to have an option in the preferences to turn on or off the ability to turn pages with the mouse wheel?  And if on, it acts like your first suggestion above.

Regardless of what you do, thanks for considering my suggestion!

**Comment by binarynonsense** [comment]
That was really helpful. I'd have to think about it, test the different ideas and probably add and option to switch them on and off if I add some of these. I don't know when/if I'll have the time to work on the next version but if I can in the future I'd like to try.
Thanks for the suggestions!

**Comment by babeslooker** [comment]
Hi, I would be happy if you owner add mouse wheel/middle **scroll click** feature (also option to switch them on and off if you want to) like infinite/continuous scroll/ long strip reading mode that is typically needed for reading Webtoon to the next update. Thanks in advance!

**Comment by binarynonsense** [comment]
As I mentioned above, continuous page mode is something I'd like to try adding some day but probably not for the next update, as it will probably take a lot of work/changes to the way I display pages.  Like with the previous suggestion, I don't know when/if I'll have the time to work on it, or even the next big version, but if I can in the future I'd like to try.
Thanks for the suggestion!

**Comment by binarynonsense** [comment]
@Kered  Sorry it took me so long, but I've finally added an option to the preferences to automatically turn the page when a scroll boundary is reached (i.e. if you keep scrolling after reaching the top/bottom of the page the previous/next page will be loaded)

It's available in the latest beta ([2.4.5-beta3](https://github.com/binarynonsense/comic-book-reader/releases/tag/v2.4.5-beta3)), and disabled by default.

**Comment by Kered** [comment]
Looks like it works great - thanks so much for adding that option!

**Comment by binarynonsense** [comment]
No problem! Thanks for testing it, glad it works.
