### ISSUE TITLE
Feature Request: base 64 encoding in epub

### ISSUE THREAD

**Issue by UPSA007** [binarynonsense/comic-book-reader#29]
As you know comicbook files are very large compared to normal ebook files. Naturally they consume a lot of space which is not feasible in devices such as Android tablets. One possible solution to that is cloud but most of them require some sort of subscription if you have a large library and you can't read directly from them. Since amazon has increased their upload size it really became a relatively good option. But if you upload an epub converted from cbz it will compress the files and reduce size as well as quality drastically. From 200 mb to 7 or 8 mb. The only work around that is to encode the jpeg images into base 64 and then adding them to the epub. I was wondering if you can do something about it. Maybe a toggle in the jpeg menu. Thank You

**Comment by binarynonsense** [comment]
Encoding the images in base64 to directly insert them in the html code would make the files quite larger and would require some changes to the epub creation code, and will make them unreadable by ACBR (I currently assume images are embedded in the epub as files and extract them to display them as with any of the other formats).
It will require some changes and a bit of work for something I'm not sure many would use... I'll add it to my TODO list to at least think a little more about maybe adding a conversion option if it doesn't take too much time to implement, but no promises on when/if I'll work on it.

**Comment by UPSA007** [comment]
Thank You.

**Comment by binarynonsense** [comment]
I've uploaded a new [beta version (2.4.5-beta1)](https://github.com/binarynonsense/comic-book-reader/releases/tag/v2.4.5-beta2) that adds a new section to the Advanced options of the comic book conversion tool to allow creating epubs with the images embedded as base64 in the html.

This took me longer that I thought, as I had ditch the library I was using and code my own epub generator to be able to add support for this and other new options.

It needs more testing but seems to work fine so far (the few comics I've converted the traditional way, with the images stored as files, open correctly and although not every epub reader, including acbr at least for now, can open epubs with base64 images, some do and things look ok on them). 

Hope this helps for your intended use, let me know if that's the case or you find any problems.

**Comment by UPSA007** [comment]
Thank You. Thank you so so much. I really appreciate your kind help and hard work. :-)

**Comment by UPSA007** [comment]
Works like a charm so far. Thank You once again.

**Comment by binarynonsense** [comment]
No problem! 

If you find any problem with the new epub generation or anything that needs fixing/could be improved let me know, as I haven't had much time to test it.
