### ISSUE TITLE
Feature Request: hific integration

### ISSUE THREAD

**Issue by UPSA007** [binarynonsense/comic-book-reader#31]
I know this is maybe too much to ask but check this out.
https://hific.github.io/
This project basically integrates machine learning with compression. Results are truly impressive. Just look at those demo pictures. Even if they are ideal cases file sizes even doble or triple that size will be - well for lack of a better word miraculous. But I think for comics someone need to train the model specifically using comics. Thanks You.

**Comment by binarynonsense** [comment]
Sorry, that seems way outside the scope of the project :) 

Also, I'm happy supporting just the image formats available in chrome. They are the most commonly used ones and, as I'm using electron to make the program, I'm limited to what modern browsers like it are able to show, and libraries like sharp can convert to and from.

**Comment by UPSA007** [comment]
I'm by no sense a developer. But I deduced from the demo hific uses png as output. It simply recreates the image using Generative Adversarial Networks similar to that of stuff like upscalers like Real-ESRGAN (https://github.com/xinntao/Real-ESRGAN). Thus the output is completely free of any compression artifacts that you will get whatever method you choose to use when compressing. But you will need good model specifically trained for the type of image you want to optimise. And it is more gpu intensive to do I think.

**Comment by binarynonsense** [comment]
I just had time to give it a quick look so I may be totally wrong, but I thought the pngs are raw reconstructions (much bigger in size) of the decoded image so they can visualized. I assume there's a custom encoder AND decoder... (I found a [thread in reddit](https://www.reddit.com/r/MachineLearning/comments/hgkup5/r_highfidelity_generative_image_compression/fw4tpj5/) that seems to confirm that, as one of the authors mentions "The process to decode a PNG, compress with our method, decompress with our method and then compress a PNG is timed at 0.7 megapixels per second on a GPU.")

Anyway, my main point was implementing something like this, even if I was capable of, which I don't know (I didn't find a license, it's state-of-the-art and the code and libraries used are in python), would be too much work and outside the scope of the project. If someday there's an easy to integrate library for this that works well with electron/node I'd be up for giving it a go if I have the time, but for know I'm happy limiting myself to the commonly used formats and compression libraries.

**Comment by UPSA007** [comment]
No  worries :-)
