### ISSUE TITLE
One small question about PDF to epub conversion

### ISSUE THREAD

**Issue by UPSA007** [binarynonsense/comic-book-reader#34]
Hey sorry to bother you once again. I have one small question. I have a few PDF comics which (I was honestly surprised to find) have actual text layer that is selectable. I was just wondering what happens to those during conversion to epub? Do they just hide underneath the image with embedded text. Or do they just get removed completely. Thank You

**Comment by binarynonsense** [comment]
PDF pages are rendered and saved as images during the conversion, so the output files don't have selectable text anymore.

**Comment by UPSA007** [comment]
Oh I understand. I had an interesting experience the other day that's why I'm asking. For class we use these smart whiteboards which basically are oversized (like 75+ inch) Android tablets. So I was like let's try running a normal ebook reader app in it like moon+ or play books. My mind was literally blown. I opened Moon and Ba's Daytrppier. And it looked soo good. But I noticed that text although looks good but not like crystal shap. But then I opened something else and it was great. Thats why I was trying to figure out what was going on. Anyways it might be a good feature to implement if you have time. But no pressure. As always thank you and keep up the good work.

**Comment by binarynonsense** [comment]
Thanks for the feature suggestion, they are always appreciated but in these case, PDF reading and conversion is not likely to change. ACBR is focused on comic books and simplicity (of usage/features and, as much as possible, of development :)), converting them to images fits the goals of the project and the formats it outputs to, so I'm happy leaving it as it is.
