### ISSUE TITLE
Some essential functions

### ISSUE THREAD

**Issue by ItsukaShiroInfinity** [binarynonsense/comic-book-reader#91]
A very good program, but you should add that you can scroll by holding the mouse click, some laptop touchpalls do not have the function of emulating the mouse wheel. And also to display all the images as one (vertical strip). You can guide yourself with the tachiyomi application, it has a very good implementation of this. I have looked for a program that does this on PC and have had no results.

**Comment by binarynonsense** [comment]
Glad you like it!

- You mean clicking the left mouse button and holding it automatically scrolls the page (down?) or you have to also move the mouse up and down to scroll? (I've no experience with that control scheme so I'm uncertain what would be expected behavior).

- If you mean continuous mode, there's already [an issue](https://github.com/binarynonsense/comic-book-reader/issues/86) where I address that request but, in short: I'd like to try to add it someday (although it won't probably be in the near future) but no promises, as there are some technical challenges I'd need to figure out first and will also have to redesign a lot of the reader's code (my main goal when I started ACBR was making a simple page-by-page reader).

Thanks for the suggestions!

**Comment by binarynonsense** [comment]
>  I have looked for a program that does this on PC and have had no results.

Maybe you have already checked them but just in case: on windows I think Sumatra PDF supports continuous mode and on Linux I know Okular does  (although if what you are looking for is webtoon mode, continuous with no separation between pages, I don't know if they support it).

**Comment by binarynonsense** [comment]
> some laptop touchpalls do not have the function of emulating the mouse wheel

Another question about this request: Isn't the already available alternative way to scroll the page, using the arrow keys, a good enough alternative for those using a laptop without mousewheel emulation? or is it something you find worse in some way and would really prefer to also have the option of using the control scheme you suggested? Seems like using the arrows would be more comfortable than holding the mouse button and moving the mouse on a laptop's touchpad...

**Comment by binarynonsense** [comment]
It's been 2 weeks without a response so I'm going to close this issue, but feel free to reopen it if you want to resume it.

**Comment by binarynonsense** [comment]
It's been 2 weeks without a response so I'm going to close this issue, but feel free to reopen it if you want to resume it.

**Comment by ItsukaShiroInfinity** [comment]
> > Algunas pantallas táctiles de portátiles no tienen la función de emular la rueda del ratón.
> 
> Otra pregunta sobre esta solicitud: ¿No es la forma alternativa ya disponible de desplazarse por la página, usando las teclas de flecha, una alternativa suficientemente buena para quienes usan una computadora portátil sin emulación de rueda del mouse? ¿O es algo que le parece peor de alguna manera y realmente preferiría tener también la opción de utilizar el esquema de control que sugirió? Parece que usar las flechas sería más cómodo y sencillo que mantener presionado el botón izquierdo y deslizarse verticalmente en el panel táctil de una computadora portátil...

Apparently you haven't noticed it but when reading a manga it is necessary to go and go up in an image but the arrows do not offer that precision when moving to the corresponding box and it can be choppy

**Comment by ItsukaShiroInfinity** [comment]
> > He buscado un programa que haga esto en PC y no he obtenido resultados.
> 
> Quizás ya los hayas comprobado pero por si acaso: en windows creo que Sumatra PDF soporta el modo continuo y en Linux sé que Okular sí (aunque si lo que buscas es el modo webtoon, continuo y sin separación entre páginas, no lo hago). saber si lo apoyan).

I like how your program is designed and the specialization it is aimed at. If you wonder if the "continuous strip" and "discontinuous strip" functions can be accepted or not, just launch a kind of statement or vote to see if users accept it. If the idea is welcome you can think about maybe adding it.

**Comment by binarynonsense** [comment]
> I like how your program is designed and the specialization it is aimed at. If you wonder if the "continuous strip" and "discontinuous strip" functions can be accepted or not, just launch a kind of statement or vote to see if users accept it. If the idea is welcome you can think about maybe adding it.

No need to make a poll or anything like that, I already think it's something some people could find useful (like I pointed out before, there even already is an [open issue focused on this feature](https://github.com/binarynonsense/comic-book-reader/issues/86) where I talked a bit about it) and it's always been something I'd be interested in adding at some point if I can, but there are time restrictions and some technical and design reasons that may make it not a priority and maybe even not feasible at least for now. As I said originally: 
> I'd like to try to add it someday (although it won't probably be in the near future) but no promises, as there are some technical challenges I'd need to figure out first and will also have to redesign a lot of the reader's code (my main goal when I started ACBR was making a simple page-by-page reader).

**Comment by binarynonsense** [comment]
> > > Algunas pantallas táctiles de portátiles no tienen la función de emular la rueda del ratón.
> > 
> > 
> > Otra pregunta sobre esta solicitud: ¿No es la forma alternativa ya disponible de desplazarse por la página, usando las teclas de flecha, una alternativa suficientemente buena para quienes usan una computadora portátil sin emulación de rueda del mouse? ¿O es algo que le parece peor de alguna manera y realmente preferiría tener también la opción de utilizar el esquema de control que sugirió? Parece que usar las flechas sería más cómodo y sencillo que mantener presionado el botón izquierdo y deslizarse verticalmente en el panel táctil de una computadora portátil...
> 
> Apparently you haven't noticed it but when reading a manga it is necessary to go and go up in an image but the arrows do not offer that precision when moving to the corresponding box and it can be choppy

Then using the arrows would be an acceptable solution but your problem is with the sensibility/smoothness of the scroll using them? I could add an option in the preferences to set the scroll jump using the arrows bigger or smaller.

**Comment by binarynonsense** [comment]
> I could add an option in the preferences to set the scroll jump using the arrows bigger or smaller...

Would you find that useful?

**Comment by ItsukaShiroInfinity** [comment]
> > Al parecer no te has dado cuenta pero al leer un manga es necesario ir y subir en una imagen pero las flechas no ofrecen esa precisión al pasar al cuadro correspondiente y puede quedar entrecortada
> 
> Entonces, usar las flechas sería una solución aceptable, pero ¿su problema es la sensibilidad/suavidad del desplazamiento al usarlas? Podría agregar una opción en las preferencias para configurar el salto de desplazamiento usando las flechas más grandes o más pequeñas...

**Comment by binarynonsense** [comment]
At first you mentioned it would be a way to emulate the mouse wheel for people with laptops without one, or a way to emulate it, so I got a bit confused as to why using the arrows wouldn't be ok.

If I understand it correctly now, you can already do that using the scrollbar, clicking and dragging it to more precisely move the page up and down but, as an extra, you'd like to also be able to do the same by clicking + dragging anywhere on the page... is that more or less it?

PS: I see you are translating the texts to Spanish when you quote them, if you feel more comfortable using it we can continue the conversation in Spanish instead of English if you want, it's fine by me either way.

**Comment by ItsukaShiroInfinity** [comment]
Eso mismo es a lo que me refiero. Clic + arrastre en cualquier sitio. Personalmente no me gusta tener la barra lateral de desplazamiento. Además también sirve para cuando una imagen es más ancha que lo que se muestra en pantalla moverse izquierda-derecha. (Aunque personalmente ajusto la imagen al ancho de la ventana.)

**Comment by binarynonsense** [comment]
En el caso de que la página sea más ancha también aparece una barra de scroll horizontal para moverla, así que siempre se podría usar eso pero veo la utilidad de esta alternativa (yo también desactivo las barras, y ajusto al ancho, cuando uso el programa, aunque en mi caso con la rueda del ratón o las flechas del teclado me basta).

Añadiré el click+arrastre de la página a mi lista de cosas a intentar incluir en el programa en el futuro, cuando tenga tiempo para dedicar a trabajar en ACBR (ahora mismo no puedo). No prometo nada, parece algo no demasiado complicado pero no se sabe hasta que uno se pone, ni sé cuándo podré ponerme con ello, pero lo intentaré algún día.

**Comment by binarynonsense** [comment]
Más vale tarde que nunca: acabo de subir una nueva beta, [v3.5.0-beta1 ](https://github.com/binarynonsense/comic-book-reader/releases/tag/v3.5.0-beta1), en la que funciona lo que habíamos hablado: click+arrastrar para hacer scroll de la página. Ya me dirás si lo pruebas y hace lo que querías.

**Comment by binarynonsense** [comment]
Just released the next stable release containing the changes I mentioned so I'll close this issue.
